"""add_verification_columns

Revision ID: c301b2e7bdfd
Revises: a65e89f1644b
Create Date: 2026-03-21 20:31:02.826422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c301b2e7bdfd'
down_revision: Union[str, Sequence[str], None] = 'a65e89f1644b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
