"""add_is_recurring

Revision ID: c627bd845ba8
Revises: a582dd7c9947
Create Date: 2026-03-21 21:01:06.054576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c627bd845ba8'
down_revision: Union[str, Sequence[str], None] = 'a582dd7c9947'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('is_recurring', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'is_recurring')
    # ### end Alembic commands ###
